### ISSUE TITLE
a soundness bug (perhaps due to mishandling of parameter passing?) 

### ISSUE THREAD

**Issue by zhendongsu** [TrustInSoft/tis-interpreter#136]
``` c
$ tis-interpreter.sh test.c
[value] Analyzing a complete application starting at main
[value] Computing initial state
[value] Initial state computed

100

[value] done for function main
$ 
$ cat test.c
int printf (const char *, ...); 

int a = 100; 

void foo (int p)
{
  a = 0;
}

int main ()
{
  foo (a);
  printf ("%d\n", a); 
  return 0; 
}
$ 
```

**Comment by regehr** [comment]
It's crazy that we ran tis-interpreter on so many interesting codes and never ran into this!

**Comment by zhendongsu** [comment]
I've been doing some testing of the tis-interpreter itself lately.  More to come. :)

**Comment by regehr** [comment]
Cool! It might be worth getting a more recent snapshot of the tool from Pascal if he has time to prepare one.

**Comment by pascal-cuoq** [comment]
Well found. This is one case where the sophistication of the analyzer leads to bugs that would not have happened in an interpreter written from scratch.

**Comment by zhendongsu** [comment]
@pascal-cuoq I'd certainly almost agree with you, Pascal, but "... would not have happened ..." would be a bit too strong --- anything could happen of course.

**Comment by pascal-cuoq** [comment]
Let me put it this way then: the fix only deletes code. The code would not have existed in the first place if tis-interpreter did not originate from a static analyzer.
