### ISSUE TITLE
Please document the dependencies properly

### ISSUE THREAD

**Issue by Earnestly** [TrustInSoft/tis-interpreter#30]
* ocaml 4.02.3
* linux 4.4.5
* gcc 5.3.0

Following the procedure from the `INSTALL.md` using `--prefix=/usr` with the mentioned Zarith dependency installed under `/usr/lib/ocaml/zarith` results in the following error:

```
File "src/libraries/stdlib/integer.mli", line 26, characters 9-12:
Error: Unbound module Z
```

Why would the configure phase allow me to continue if it's going to fail?

Neverminding that I added `--enable-zarith=/usr/lib/ocaml/zarith` which seems to have worked, but half way through the build I'm once again faced with repeated errors from ocamlfind:

```
ocamlfind: Package `easy-format' not found
ocamlfind: Package `biniou' not found
ocamlfind: Package `yojson' not found
```

Culminating in with a confused `ocamlc`:

```
ocamlc.opt: don't know what to do with src/plugins/rte.
Usage: ocamlc <options> <files>
...
share/Makefile.generic:70: recipe for target 'src/plugins/rte/visit.cmi' failed
make: *** [src/plugins/rte/visit.cmi] Error
ocamlc.opt: don't know what to do with src/plugins/value.
Usage: ocamlc <options> <files>
...
share/Makefile.generic:70: recipe for target 'src/plugins/value/legacy/valarms.cmi' failed
make: *** [src/plugins/value/legacy/valarms.cmi] Error 2
ocamlc.opt: don't know what to do with src/plugins/value.
Usage: ocamlc <options> <files>
...
share/Makefile.generic:70: recipe for target 'src/plugins/value/slevel/stop_at_nth.cmi' failed
```

In order to package this I'd like documentation on what the needed dependencies are along with explicitly mentioning which of them is a runtime dependency and which is a compile time dependency.

I would like to avoid crawling through various project CIs in order to determine this information, or if that's how you wish to proceed then at least provide a link to it in something resembling an INSTALL or README file.

**Comment by pascal-cuoq** [comment]
I do not have a solution to this problem. I did not write the code that has these dependencies, I only use it. The only thing I can do to help is to make binaries so that others do not have to. One recent binary is available for Linux from http://trust-in-soft.com/tis-interpreter . Please wait for the next one if this one is already too old, the next one will arrive earlier than easy OCaml dependencies.

**Comment by Earnestly** [comment]
What?

**Comment by Earnestly** [comment]
Why is this closed?  Just because you claim it's not ready for packaging (even though you claim to not know the code) doesn't mark it solved in any way.

And yes, the more documentation about the build the better.  This allows you to clearly communicate with others about the kinds of things they should expect and potential issues they have to face. 

Obviously a link, or indication, is better than nothing if the CI script is the canonical representation.  On the other hand, clear and well written documentation is better.
