### ISSUE TITLE
Assistance with error - false positive?

### ISSUE THREAD

**Issue by technion** [TrustInSoft/tis-interpreter#36]
Hi,

Apologies if this is misplaced as an "issue" - I couldn't locate any discussion groups and I doubt there's an active tis-interpreter tag on SO. If there's a better place to take this, please let me know.

I've been running against the Argon2 library. After some code changes so that it didn't fail on pthreads, I'm seeing this error:

```
/code/src/blake2/blake2b.c:195:[kernel] warning: accessing uninitialized left-value:
                  assert \initialized(&m[blake2b_sigma[r][2*0+0]]);
                  stack: blake2b_compress :: /code/src/blake2/blake2b.c:229 <-
                         blake2b_update :: /code/src/blake2/blake2b.c:339 <-
                         blake2b_long :: /code/src/core.c:145 <-
                         finalize :: /code/src/argon2.c:75 <-
```

The file in question is here:

https://github.com/P-H-C/phc-winner-argon2/blob/master/src/blake2/blake2b.c

And the line in question reduces down to:

    v[0] = v[0] + v[1] + m[0];

Both v[0] and m[0] are initialised earlier in that function, so every possible interpretation I have of this is that it's a false positive. Unfortunately the analyser then refuses to go on and analyse the rest of the codebase.

- Have I read this error correctly? Could it be referring to a genuine bug in a way I am not seeing?
- If this is a false positive, how can I go on to analyse the rest of the application? I have played around with using memset to zero out m[] and the error did not go away (further suggesting there is something else going on).

Finally, thank you for this product. It's something the industry has needed.

**Comment by pascal-cuoq** [comment]
Hello,

I am going to help with the diagnosis during the day. If everything necessary to reproduce already included in your report (all the files used, commandline?)

The message is saying that `&m[blake2b_sigma[r][2*0+0]]` is uninitialized, that is, some location inside `m`.

If I remember correctly, inserting `Frama_C_show_each(m);` just before the problematic line will make the interpreter display the contents of `m` each time that line is executed, but I would have to check (in the worst case it will show what happens when the expression `m` decays to a pointer, that is, `&m`).

**Comment by technion** [comment]
Hi,

Many thanks for your assistance. I have created a github branch that includes all the code changes I made to get this far and replicate this. At this point, only the most recent commit deviates from the official source. You may note I had to remove the secure memset function, which tis-interpreter did not like (I did not record the errors). I suspect it won't function properly in practice due to my pthread stubs, but I can cross that bridge too when I come to it.

This branch can be seen here:

https://github.com/technion/phc-winner-argon2/tree/tis_stubs

The file run.sh contains the exact commands used to replicate this error.

I've inserted the relevant commands and it definitely produces the error right after:

    [value] Called Frama_C_show_each_index({0})

But what this interestingly reveals is that it runs through the function many times, and seems to successfully complete calls with a value of 0 many times before producing the given error. Will continue to investigate with this information.

**Comment by pascal-cuoq** [comment]
I should also explain that transferring a slice of uninitialized memory from one memory location to another without any computation is allowed by the interpreter (structs need to be copiable from one place to the other, and structs contain padding). So although the function seems to initialize all of `m` [here](https://github.com/technion/phc-winner-argon2/blob/a694398a6c5e83609cafb663a4d83b2d96cddbdc/src/blake2/blake2b.c#L154), the problem could be that `load64` returned a slice of uninitialized memory at some point.

**Comment by technion** [comment]
I have made a commit which shows the logging commands inserted:
https://github.com/technion/phc-winner-argon2/commit/a694398a6c5e83609cafb663a4d83b2d96cddbdc

And the output:
https://raw.githubusercontent.com/technion/phc-winner-argon2/tis_stubs/wut.txt

load64 is fairly trivial and I expect any legit issue is further up the chain. Of course, happy to be wrong.

**Comment by pascal-cuoq** [comment]
Here is some more instrumentation.

```
int blake2b_update(blake2b_state *S, const void *in, size_t inlen) {
  Frama_C_show_each_state1(*S);
    const uint8_t *pin = (const uint8_t *)in;

    if (inlen == 0) {
        return 0;
    }

    /* Sanity check */
    if (S == NULL || in == NULL) {
        return -1;
    }

    /* Is this a reused state? */
    if (S->f[0] != 0) {
        return -1;
    }

    if (S->buflen + inlen > BLAKE2B_BLOCKBYTES) {
        /* Complete current block */
        size_t left = S->buflen;
        size_t fill = BLAKE2B_BLOCKBYTES - left;
        memcpy(&S->buf[left], pin, fill);
  Frama_C_show_each_state2(*S);	
        blake2b_increment_counter(S, BLAKE2B_BLOCKBYTES);
        blake2b_compress(S, S->buf);
```
When I recommended `Frama_C_show_each_m(m);`, I was hoping we would see the contents of the array `m`. Unfortunately, `m` decays into a pointer when assed as argument and then the logging function shows the value of the pointer. This is fixable but let's do with what we have.

The pointer decay problem doesn't happen with structs, so above I am printing the contents of the entire struct of type `blake2b_state`. The log is as follows:

```
…
[value] Called Frama_C_show_each_state1(.h[0] ∈ {7640891576939301160}
                                        .h[1] ∈ {13503953896175478587}
                                        .h[2] ∈ {4354685564936845355}
                                        .h[3] ∈ {11912009170470909681}
                                        .h[4] ∈ {5840696475078001361}
                                        .h[5] ∈ {11170449401992604703}
                                        .h[6] ∈ {2270897969802886507}
                                        .h[7] ∈ {6620516959819538809}
                                        {.t[0..1]; .f[0..1]} ∈ {0}
                                        .buf[bits 0 to 31] ∈ {32}
                                        .buf[4..127] ∈ {0}
                                        .buflen ∈ {4}
                                        .outlen ∈ {32}
                                        {.last_node; .[bits 1864 to 1919]} ∈ {0})
        stack: Frama_C_show_each_state1 :: src/blake2/blake2b.c:209 <-
               blake2b_update :: src/blake2/blake2b.c:343 <-
               blake2b_long :: src/core.c:148 <-
               finalize :: src/argon2.c:75 <-
               argon2_ctx :: src/argon2.c:129 <-
               argon2_hash :: src/test.c:31 <-
               hashtest :: src/test.c:62 <-
               main
[value] Called Frama_C_show_each_state2(.h[0] ∈ {7640891576939301160}
                                        .h[1] ∈ {13503953896175478587}
                                        .h[2] ∈ {4354685564936845355}
                                        .h[3] ∈ {11912009170470909681}
                                        .h[4] ∈ {5840696475078001361}
                                        .h[5] ∈ {11170449401992604703}
                                        .h[6] ∈ {2270897969802886507}
                                        .h[7] ∈ {6620516959819538809}
                                        {.t[0..1]; .f[0..1]} ∈ {0}
                                        .buf[bits 0 to 31] ∈ {32}
                                        .buf[4..127] ∈ UNINITIALIZED
                                        .buflen ∈ {4}
                                        .outlen ∈ {32}
                                        {.last_node; .[bits 1864 to 1919]} ∈ {0})
        stack: Frama_C_show_each_state2 :: src/blake2/blake2b.c:231 <-
               blake2b_update :: src/blake2/blake2b.c:343 <-
               blake2b_long :: src/core.c:148 <-
               finalize :: src/argon2.c:75 <-
               argon2_ctx :: src/argon2.c:129 <-
               argon2_hash :: src/test.c:31 <-
               hashtest :: src/test.c:62 <-
               main
[value] Called Frama_C_show_each_index({0})
        stack: Frama_C_show_each_index :: src/blake2/blake2b.c:197 <-
               blake2b_compress :: src/blake2/blake2b.c:233 <-
               blake2b_update :: src/blake2/blake2b.c:343 <-
               blake2b_long :: src/core.c:148 <-
               finalize :: src/argon2.c:75 <-
               argon2_ctx :: src/argon2.c:129 <-
               argon2_hash :: src/test.c:31 <-
               hashtest :: src/test.c:62 <-
               main
src/blake2/blake2b.c:197:[kernel] warning: accessing uninitialized left-value:
                  assert \initialized(&m[blake2b_sigma[r][2*0+0]]);
                  stack: blake2b_compress :: src/blake2/blake2b.c:233 <-
                         blake2b_update :: src/blake2/blake2b.c:343 <-
                         blake2b_long :: src/core.c:148 <-
                         finalize :: src/argon2.c:75 <-
                         argon2_ctx :: src/argon2.c:129 <-
                         argon2_hash :: src/test.c:31 <-
                         hashtest :: src/test.c:62 <-
                         main
```

It shows that `S->buf` was initialized completely when the function was entered, but that after the `memcpy`, it contains some uninitialized bits. So the contents pointed by `pin` (that is, by the pointer `in`, argument of `blake2b_update`) are to blame here.

The address of a variable `blockhash_bytes` has been passed as `in`.

**Comment by pascal-cuoq** [comment]
`instance.memory` points to a block that was allocated by `malloc` in function `argon2_hash` at line [105](https://github.com/technion/phc-winner-argon2/blob/79442a82a85344cf5d52129199a01ac45ac3739d/src/argon2.c#L105) and, according to a `Frama_C_dump_each();` inserted [here](https://github.com/technion/phc-winner-argon2/blob/79442a82a85344cf5d52129199a01ac45ac3739d/src/argon2.c#L74), it still hasn't been written to at that point. It probably should have. It seems ineluctable that uninitialized memory will be used when line 74 is reached in these conditions, and that the memory should have been initialized somehow between the moment it was allocated and line 74 if execution was going to continue that way.

**Comment by pascal-cuoq** [comment]
To confirm that the behavior does not come from tis-interpreter, and perhaps to make the problem reportable to the authors, I would fill the block allocated at [line 105](https://github.com/technion/phc-winner-argon2/blob/79442a82a85344cf5d52129199a01ac45ac3739d/src/argon2.c#L105) with `0xdeadbeef` and show that the `0xdeadbeef` bytes are incorporated in a computation much, much later on.

**Comment by technion** [comment]
I've created a memset() in allocate_memory() which should ensure everything that gets malloc()'ed ends up initialised down to the segments you've helped direct us to. tis-interpreter still appears to fail with a similar (but different) error on the same piece of code.

```/code/src/blake2/blake2b.c:197:[value] warning: The following sub-expression cannot be evaluated:
                 (v[0] + v[4]) + m[blake2b_sigma[r][2 * 0 + 0]]

                 All sub-expressions with their values:
                 int  2 * 0 + 0 ∈ {0}
                 uint64_t  v[0] + v[4] ∈ {13481588052017302521}
                 int  2 * 0 ∈ {0}
                 uint64_t  m[blake2b_sigma[r][2 * 0 + 0]] ∈ [0..18446744073709551615]
                 uint64_t  v[0] ∈ {7640891576939301160}
                 uint64_t  v[4] ∈ {5840696475078001361}
                 unsigned int  r ∈ {0}
                 unsigned int  blake2b_sigma[r][2 * 0 + 0] ∈ {0}
                 int  0 ∈ {0}
                 int  2 ∈ {2}
                 int  4 ∈ {4}

                 Stopping
                 stack: blake2b_compress :: /code/src/blake2/blake2b.c:231 <-
```

Am continuing to investigate.

**Comment by technion** [comment]
I'm currently hitting a wall around the fact that anything that writes out the relevant memory and removes this issue, causes the above error, in the same piece of code.

Given that it knows v[0], v[4], that

    unsigned int  blake2b_sigma[r][2 * 0 + 0] ∈ {0}

And a frame dump appears to show m[0] is initialized (not with the values I've set at malloc() time):

    m[0][bits 0 to 31] ∈ {32}

**Comment by pascal-cuoq** [comment]
Going back to the original issue first:

when you model `pthread_create` as [doing nothing](https://github.com/technion/phc-winner-argon2/commit/53fc4bf332da5e79d6c0342c554e3de04f704249), you change the behavior of function `fill_memory_blocks` [dramatically](https://github.com/technion/phc-winner-argon2/blob/53fc4bf332da5e79d6c0342c554e3de04f704249/src/core.c#L301). The function `fill_memory_blocks` is one of the functions called [not long](https://github.com/technion/phc-winner-argon2/blob/79442a82a85344cf5d52129199a01ac45ac3739d/src/argon2.c#L69) before the problem. This function is supposed to do something, and it does much much less when `pthread_create` is a no-op. On thing it does not do when pthread is a no-op is initialize the memory that will be used later in Blake 2.

In the version that you have further modified, the following line in the log indicates that your changes have made the analyzer unable to identify the value of at least one element of `m`:
```
uint64_t  m[blake2b_sigma[r][2 * 0 + 0]] ∈ [0..18446744073709551615]
```
One the interpreter is propagating that poisoned `m`, any attempt to use it will cause interpretation to stop. It would have been better for the user if the interpreter had stopped when it was unable to compute what `m` was being set to. This can be considered as a bug, and I would be interested in knowing how you modified the analyzed code to get that message.

**Comment by technion** [comment]
I had considered, apparently naively, that with threads = 1 (which is the majority of the test suite), having pthread_create do nothing wouldn't be an issue.

    and I would be interested in knowing how you modified the analyzed code to get that message.

In argon2_hash() and allocate_memory(), I put a memset directly after the malloc(). The expectation here of course being, that should make it somewhat certain that no allocated memory is ever touched initialized. I initialized to a value of 'd' because it's more obvious to see staring at you than zeroes.

I've continued to look for a solution and I'm aware you've put a lot of time into getting things this far.

    I am putting Argon2 in my list of advanced examples to show how to analyse with tis-interpreter

I'd very much appreciate that.

**Comment by technion** [comment]
I have managed to write a threadless edition of the code, which runs without pthreads and passes all Argon2 internal tests. I have pushed this to the earlier linked branch, and hope to produce a useful result shortly using this.

**Comment by technion** [comment]
The error with the updated code is:
```
/code/src/core.c:358:[kernel] warning: accessing uninitialized left-value: assert \initialized(&context->pwd);
                  stack: validate_inputs :: /code/src/encoding.c:328 <-
                         decode_string :: /code/src/argon2.c:246 <-
                         argon2_verify :: /code/src/test.c:44 <-
                         hashtest :: /code/src/test.c:61 <-
                         main
```

This is actually a legitimate bug I caught and fixed after I forked my tis-stub version - it has been merged upstream:

https://github.com/P-H-C/phc-winner-argon2/commit/69a13b457c35afcee08d556cfaf4b1644bce4cbb

Having pulled that into my source, and drastically shrinking the test suite (or it would run for hours), it now runs to completion. I've seeing two warnings - investigating now.

**Comment by yakobowski** [comment]
Just to let you know, you will hit a problem with with the conditionals `if (rc)` in core.c. Removing the calls to thread-related functions causes `rc` to become uninitialized memory.

**Comment by technion** [comment]
@yakobowski - yes - already got that sorted. Initialising it to 0 in the first place still allows the complete existing Argon2 test suite to run.

Is there some sort of define for

    #ifdef RUNNING_TIS_INTERPRETER

I'm adding and removing comments around functions like  Frama_C_dump_each();  a bit too often.

**Comment by technion** [comment]
Looks like one legitimate issue found:

**Comment by pascal-cuoq** [comment]
tis-interpreter runs the pre-processor with `-DTIS_INTERPRETER`. If you needed more macros, you could use `tis-interpreter.sh --cc "-DANOTHER_MACRO"`

Please not that it is not calling `memset` or `memset_s` with a size of 0 that is invalid. It is calling them with an invalid pointer. In the past this was thought to be acceptable with a size of 0, but modern compilers apply optimizations that assume that the pointer arguments of these functions are valid.
