### ISSUE TITLE
No warnings: arguments to functions from ctype.h not from unsigned char or EOF

### ISSUE THREAD

**Issue by ch3root** [TrustInSoft/tis-interpreter#41]
Source code:
```c
#include <ctype.h>

int main()
{
  isdigit(1000);
  tolower(1000);
}
```

tis-interpreter (3615ce825dfb8a5e66ba60c0e62e9c2131f1cd2d) output:
```
[value] Analyzing a complete application starting at main
[value] Computing initial state
[value] Initial state computed
[value] done for function main
```

**Comment by pascal-cuoq** [comment]
My previous comment about ACSL not being interpreted by tis-interpreter only applied to functions that have been implemented in OCaml. For functions that are written in C (and there is no reason for instance not to be satisfied with a one-line C implementation for a C function such as `isdigit`), the ACSL contract is interpreted, leading to this quick fix.

**Comment by ch3root** [comment]
Thanks for the explanation and for the fix. I've heard that wrong arguments to functions from ctypes.h could lead to real problems on systems where these functions are implemented as a direct access to an array. But I haven't experienced it first-hand.
