### ISSUE TITLE
Wrong results: printf("%.d", 0)

### ISSUE THREAD

**Issue by ch3root** [TrustInSoft/tis-interpreter#45]
Source code:
```c
#include <stdio.h>

int main()
{
  printf(">%.d<\n", 0);
}
```

tis-interpreter (3615ce825dfb8a5e66ba60c0e62e9c2131f1cd2d) output:
```
[value] Analyzing a complete application starting at main
[value] Computing initial state
[value] Initial state computed

>0<

[value] done for function main
```

C11, 7.21.6.1p8: "The result of converting a zero value with a precision of zero is no characters."

gcc 6 w/ubsan output:
```
><
```

clang 3.9 w/ubsan output:
```
><
```

**Comment by pascal-cuoq** [comment]
Again, an arguable OCaml bug:
```
# Printf.printf "|%.0d|%.0Ld|\n" 0 0L ;; 
|0|0|
```

This one hasn't been fixed in the 4.03 printf revamp, so there is no argument it needs to be worked around even if I might somehow convince the OCaml developers that it is a bug.
