### ISSUE TITLE
Wrong results: printf("%05.3d\n", 1)

### ISSUE THREAD

**Issue by ch3root** [TrustInSoft/tis-interpreter#47]
Source code:
```c
#include <stdio.h>

int main()
{
  printf("%05.3d\n", 1);
}
```

tis-interpreter (3615ce825dfb8a5e66ba60c0e62e9c2131f1cd2d) output:
```
[value] Analyzing a complete application starting at main
[value] Computing initial state
[value] Initial state computed

00001

[value] done for function main
```

C11, 7.21.6.1p6: "For d, i, o, u, x, and X conversions, if a precision is specified, the 0 flag is ignored."

gcc 7 w/ubsan output:
```
printf-%d-prec-and-zero.c: In function ‘main’:
printf-%d-prec-and-zero.c:5:10: warning: '0' flag ignored with precision and ‘%d’ gnu_printf format [-Wformat=]
   printf("%05.3d\n", 1);
          ^~~~~~~~~~
  001
```

clang 3.9 w/ubsan output:
```
  001
```

**Comment by pascal-cuoq** [comment]
This tis-interpreter bug results of [an OCaml bug that has already been fixed](http://caml.inria.fr/mantis/view.php?id=6938) (the reporter of the OCaml bug is one of the contributors to tis-interpreter).

However in the spirit of being compatible with the OCaml compiler that people might have from the Linux distribution they installed 18 months ago and that was frozen 6 months before that, I'll try a workaround.

**Comment by ch3root** [comment]
Ha-ha, fixed OCaml is not even released yet, right?

Actually I don't know if it's worth to work around in tis-interpreter. I mean I reported it but I don't know if it's used in any real code. Seems quite exotic to me. But who knows...

**Comment by pascal-cuoq** [comment]
Implementing the workaround allowed me to add a warning for this situation. The warning is better for beginners than Clang's absence of warning and than GCC's static warning that applies even if the precision is dynamic and negative, so there is value in it. One thing I think tis-interpreter should be good for eventually is as a teaching tool (and bad as C might be, it's worth teaching it to at least a few if we do not want a big scare in 2038).

```
$ cat t.c
#include <stdio.h>

int main()
{
  printf("%05.*d\n", -1, 1);

  printf("%05.*d\n", 2, 1);

  printf("%05.2d\n", 1);
}
$ ./tis-interpreter/tis-interpreter.sh t.c
[value] Analyzing a complete application starting at main
[value] Computing initial state
[value] Initial state computed

00001

t.c:7:[value] warning: both '0' flag and precision when printing integer. Ignoring '0' flag

   01

t.c:9:[value] warning: both '0' flag and precision when printing integer. Ignoring '0' flag

   01

[value] done for function main
```
