### ISSUE TITLE
No warnings: partially overlapping lvalue assignment for objects of size <= 4 bytes

### ISSUE THREAD

**Issue by ch3root** [TrustInSoft/tis-interpreter#60]
Source code:
```c
#include <stdio.h>

int main()
{
  struct s {
    char s[3];
  } ab = {"ab"};

  union {
    struct {
      struct s s1;
      char eol1;
    };
    struct {
      char c;
      struct s s2;
      char eol2;
    };
  } u;

  u.s1 = ab;
  printf("%s -> ", u.s1.s);
  u.s2 = u.s1; // (1)
  u.eol2 = 0;
  printf("%s\n", u.s2.s);
  
  u.s2 = ab;
  printf("%s -> ", u.s2.s);
  u.s1 = u.s2; // (2)
  u.eol1 = 0;
  printf("%s\n", u.s1.s);
}
```

tis-interpreter (429543c4b7e9e4751f9e29b5a2f9686594e0b322) output:
```
[value] Analyzing a complete application starting at main
[value] Computing initial state
[value] Initial state computed

ab -> 

ab


ab -> 

ab

[value] done for function main
```

gcc 7 w/ubsan output:
```
ab -> abb
ab -> ab
```

clang 3.9 w/ubsan output:
```
ab -> ab
ab -> a
```

C11, 6.5.16.1p3: "If the value being stored in an object is read from another object that overlaps in any way the storage of the first object, then the overlap shall be exact and the two objects shall have qualified or unqualified versions of a compatible type; otherwise, the behavior is undefined."

We see that the code from gcc is wrong for (1) and the code from clang is wrong for (2) so this UB is a problem in practice.

**Comment by pascal-cuoq** [comment]
Congratulations for:
- finding the warning
- finding the limitation for size <= sizeof(int) (that I thought would avoid many false positives in static analysis, for a warning that most programmers do not even know they want)
- finding the program that shows that the limitation is unsound.

**Comment by ch3root** [comment]
I guess length 3 is the only one problematic, lengths 2 and 4 seems safe in practice on my machine. But who knows what will break on other architectures...

Well, what about this:

Source code:
```c
#include <stdlib.h>
#include <string.h>

int main()
{
  int x = 0;
  x = *(char *)&x;

  int *p = malloc(100);
  memset(p, 0, 100);  *(unsigned int *)p = *(int *)p;
  memset(p, 0, 100);  *(double *)p = *(float *)p;
  memset(p, 0, 100);  *(long *)p = *(double *)p;

  union {
    long l;
    int i;
  } u = {0};
  u.i = u.l;
}
```

tis-interpreter (274be6de79973f11ab62a3c77d0981882734cb2d) output:
```
[value] Analyzing a complete application starting at main
[value] Computing initial state
[value] Initial state computed
[value] done for function main
```

**Comment by pascal-cuoq** [comment]
The assignments in your last example have conversions. My interpretation of 6.5.16.1p3 is that it does not apply in this case (a converted value is written to memory, not the value being read), and I have not seen any compiler that generated code where the result was not what you would expect. Have you seen Clang or GCC produce code that does the wrong thing for any of these statements?

**Comment by ch3root** [comment]
I haven't seen problems with such code in practice but I've found  a quote for you: "An implementation need not correctly perform an assignment between overlapping operands. Overlapping operands occur most naturally in a union, where assigning one field to another is often desirable to effect a type conversion in place. The assignment may well work properly in all simple cases, but it is not maximally portable. Maximally portable code should use a temporary variable as an intermediate in such an assignment." C99Rationale, 6.5.16.1l32.
